/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.fluxocaixa.event.contapagar;

import br.com.kerubin.api.messaging.core.DomainEvent;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ContaPagarEvent implements DomainEvent {
	
	public static final String CONTA_PAGAR_CONTAPAGA = "contaPagarContaPaga";
	public static final String CONTA_PAGAR_CONTAESTORNADA = "contaPagarContaEstornada";
	
	private java.util.UUID id;
	
	private String descricao;
	
	private java.util.UUID planoContas;
	
	private FormaPagamento formaPagamento;
	
	private java.util.UUID contaBancaria;
	
	private java.util.UUID cartaoCredito;
	
	private java.util.UUID fornecedor;
	
	private Boolean contaPaga;
	
	private java.time.LocalDate dataPagamento;
	
	private java.math.BigDecimal valorPago;
	
	private String numDocumento;
	
	private TipoPagamentoConta tipoPagamento;
	
	private java.util.UUID contaPagarPai;
	
}
