/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.fluxocaixa.entity.banco;



public interface BancoAutoComplete {

	java.util.UUID getId();
	
	String getNumero();
	
	String getNome();
	
	void setId(java.util.UUID id);
	
	void setNumero(String numero);
	
	void setNome(String nome);

}
