/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.fluxocaixa.entity.bandeiracartao;



public interface BandeiraCartaoAutoComplete {

	java.util.UUID getId();
	
	String getNomeBandeira();
	
	void setId(java.util.UUID id);
	
	void setNomeBandeira(String nomeBandeira);

}
