/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.fluxocaixa.entity.banco;

import lombok.Getter;
import lombok.Setter;

@Getter @Setter
public class BancoAutoCompleteImpl implements BancoAutoComplete {

	private java.util.UUID id;
	
	private String numero;
	
	private String nome;
	
	public BancoAutoCompleteImpl() {
		// Contructor for reflexion, injection, Jackson, QueryDSL, etc proposal.
	}

}
