/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.fluxocaixa.entity.caixalancamento;



public interface CaixaLancamentoAutoComplete {

	java.util.UUID getId();
	
	String getDescricao();
	
	short getVersion();
	
	void setId(java.util.UUID id);
	
	void setDescricao(String descricao);
	
	void setVersion(short version);

}
