/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.fluxocaixa.entity.caixalancamento;

public class CaixaLancamentoSumFields {
	
	private java.math.BigDecimal sumValorCredito;
	
	private java.math.BigDecimal sumValorDebito;
	
	public CaixaLancamentoSumFields() {
		// Contructor for reflexion, injection, Jackson, QueryDSL, etc proposal.
	}
	
	public java.math.BigDecimal getSumValorCredito() {
		return sumValorCredito;
	}
	
	public java.math.BigDecimal getSumValorDebito() {
		return sumValorDebito;
	}
	
	public void setSumValorCredito(java.math.BigDecimal sumValorCredito) {
		this.sumValorCredito = sumValorCredito;
	}
	
	public void setSumValorDebito(java.math.BigDecimal sumValorDebito) {
		this.sumValorDebito = sumValorDebito;
	}

}
