/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.fluxocaixa.entity.contabancaria;

import lombok.Getter;
import lombok.Setter;

@Getter @Setter
public class ContaBancariaAutoCompleteImpl implements ContaBancariaAutoComplete {

	private java.util.UUID id;
	
	private String nomeTitular;
	
	private String numeroConta;
	
	public ContaBancariaAutoCompleteImpl() {
		// Contructor for reflexion, injection, Jackson, QueryDSL, etc proposal.
	}

}
