/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.fluxocaixa;

import org.springframework.stereotype.Component;

@Component
public class TestVisitorDefaultImpl implements TestVisitor {
	
	@Override
	public void visit(FinanceiroFluxoCaixaBaseEntityTest testInstance, String testMethodName, Object testSubject, TestOperation testOperation) {
		
		// Do nothing for default, can be specialized by sub classes.
		
	}

}
