/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.fluxocaixa;


public interface TestVisitor {
	
	void visit(FinanceiroFluxoCaixaBaseEntityTest testInstance, String testMethodName, Object testSubject, TestOperation testOperation);

}
