/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.fluxocaixa.entity.cartaocredito;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.transaction.annotation.Transactional;
import java.util.Collection;
import org.springframework.data.repository.query.Param;

@Transactional(readOnly = true)
public interface CartaoCreditoRepository extends JpaRepository<CartaoCreditoEntity, java.util.UUID>, QuerydslPredicateExecutor<CartaoCreditoEntity> {
	
	@Transactional
	@Modifying
	@Query("delete from CartaoCreditoEntity cce where cce.id in ?1")
	void deleteInBulk(java.util.List<java.util.UUID> idList);
	
	
	// WARNING: supports only where clause with like for STRING fields. For relationships entities will get the first string autocomplete key field name.
	@Query("select distinct ac.id as id, ac.nomeTitular as nomeTitular, ac.numeroCartao as numeroCartao from CartaoCreditoEntity ac where ( upper(ac.nomeTitular) like upper(concat('%', :query, '%')) ) or ( upper(ac.numeroCartao) like upper(concat('%', :query, '%')) ) order by 1 asc")
	Collection<CartaoCreditoAutoComplete> autoComplete(@Param("query") String query);
}
