/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.fluxocaixa.entity.caixa;



public interface CaixaAutoComplete {

	java.util.UUID getId();
	
	String getNome();
	
	short getVersion();
	
	void setId(java.util.UUID id);
	
	void setNome(String nome);
	
	void setVersion(short version);

}
