/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.fluxocaixa.entity.contabancaria;



public interface ContaBancariaAutoComplete {

	java.util.UUID getId();
	
	String getNomeTitular();
	
	String getNumeroConta();
	
	void setId(java.util.UUID id);
	
	void setNomeTitular(String nomeTitular);
	
	void setNumeroConta(String numeroConta);

}
