/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.fluxocaixa.messaging;

public class EventMessageNotHandledException extends RuntimeException {

	private static final long serialVersionUID = 1L;
	
	public EventMessageNotHandledException(String message) {
		super(message);
	}

}

