/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.fluxocaixa.messaging;

import java.text.MessageFormat;

import org.springframework.amqp.core.Queue;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

import br.com.kerubin.api.financeiro.fluxocaixa.FinanceiroFluxoCaixaConstants;
import br.com.kerubin.api.messaging.core.DomainEventConstants;

@ComponentScan({"br.com.kerubin.api.messaging.core"})
@Configuration
public class FinanceiroFluxoCaixaEventConfig {
	
	public static final String FINANCEIRO_FLUXO_CAIXA_QUEUE = "financeiroFluxoCaixaQueue";
	
	@Bean
	public Queue financeiroFluxoCaixaQueue() {
		// Default queue for this service.
		String queueName = MessageFormat.format("{0}_{1}_{2}", //
			DomainEventConstants.APPLICATION, //
			FinanceiroFluxoCaixaConstants.DOMAIN, //
			FinanceiroFluxoCaixaConstants.SERVICE); //
		
		return new Queue(queueName, true);
	}

}

