/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.fluxocaixa.entity.caixalancamento;

import lombok.Getter;
import lombok.Setter;

@Getter @Setter
public class CaixaLancamentoAutoCompleteImpl implements CaixaLancamentoAutoComplete {

	private java.util.UUID id;
	
	private String descricao;
	
	private short version = 0;
	
	public CaixaLancamentoAutoCompleteImpl() {
		// Contructor for reflexion, injection, Jackson, QueryDSL, etc proposal.
	}

}
