/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.fluxocaixa.entity.agenciabancaria;



public interface AgenciaBancariaAutoComplete {

	java.util.UUID getId();
	
	String getNumeroAgencia();
	
	String getDigitoAgencia();
	
	String getEndereco();
	
	void setId(java.util.UUID id);
	
	void setNumeroAgencia(String numeroAgencia);
	
	void setDigitoAgencia(String digitoAgencia);
	
	void setEndereco(String endereco);

}
